batch_type: folded
batch_size: 10
max_epoch: 20
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
unused_parameters: true
valid_batch_size: 4

encoder: earlyfusion

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 3072
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.0003
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 8000
